wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.0
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    t:
      1:
      - 1
      - 5
      - 11
      4: 3.8.10
      5: 0.11.0
      6: 4.38.2
      8:
      - 5
